### ISSUE TITLE
RuntimeException

### ISSUE THREAD

**Issue by nickchang** [jmikola/mongoqp#15]
RuntimeException: exception: JavaScript execution failed: TypeError: Object -1 has no method 'substr' near '[command].substr(0, 7) === "system.") ' (line 31)

**Comment by sergeygolubev** [comment]
I got the same issue

**Comment by jmikola** [comment]
This looks like a duplicate of #13 and will be fixed soon.

**Comment by jmikola** [comment]
Fixed by https://github.com/jmikola/mongoqp/commit/415de4c99f386fa427408071b12277c567242f37.
