### ISSUE TITLE
Runtime Exception OS X

### ISSUE THREAD

**Issue by lporras** [jmikola/mongoqp#18]
Hey guys,

I'm trying to install mongoqp on my local machine, but I have this error:

<img width="1272" alt="screen shot 2015-07-23 at 10 40 54 am" src="https://cloud.githubusercontent.com/assets/232293/8851686/752353ac-3127-11e5-8a2c-68e2fd95de4c.png">

**Comment by jmikola** [comment]
This seems to be a problem with the commit hashes listed in [`composer.lock`](https://github.com/jmikola/mongoqp/blob/master/composer.lock) pointing to some tag that was deleted upstream. I'll try to get the `composer.lock` file updated within a day or two.

In the meantime, the failed `composer create-project jmikola/mongoqp` command should still leave you with a cloned project directory. You should be able to enter that and run `composer update` to fetch newer versions of the dependencies. By default, `create-project` basically does an `install`, which attempts to get the very same versions listed in the lock file.
