### ISSUE TITLE
Crash MongoRegex not found

### ISSUE THREAD

**Issue by eduardbosch** [jmikola/mongoqp#24]
Hi,

I've just installed mongoqp to profile my db. It looks really good.

I've found and isse just installing it and clicking a db name:

<img width="1083" alt="screen shot 2017-07-24 at 17 33 12" src="https://user-images.githubusercontent.com/3925897/28531195-5c08b776-7096-11e7-97e0-b22ed0ca144f.png">

if I change the line 75 from:

`isset($collection) ? "$database.$collection" : new \MongoRegex('/^' . preg_quote("$database.") . '/'),`

to:

`isset($collection) ? "$database.$collection" : new Regex('/^' . preg_quote("$database.") . '/'),`

It's not crashing anymore, but I don't know if it keeps working as expected.

**Comment by jmikola** [comment]
It looks like I forgot to fix that in 403e4e9543e6e0d502266a5a6ae3f33be0eb5b55.

Unlike [`MongoRegex`](http://php.net/manual/en/class.mongoregex.php), [`MongoDB\BSON\Regex`](http://php.net/manual/en/mongodb-bson-regex.construct.php) takes the pattern and flags in separate arguments. The forward slashes should be omitted from the first argument:

```
new Regex('^' . preg_quote("$database."))
```

I'll fix this in the `master` branch and tag a new release shortly.

**Comment by jmikola** [comment]
Fixed: https://github.com/jmikola/mongoqp/releases/tag/v1.1.1

**Comment by eduardbosch** [comment]
Great @jmikola 🎉
